version: '3'

services:
  db-preloaded:
    #image: my-registry/my-image
    build: ./etc
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${DATABASE_NAME}
      #MYSQL_USER: ${DATABASE_USER}
      #MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
    - ./wait-for-it.sh:/tmp/wait-for-it.sh