version: '3'

services:
  db-preloaded:
    image: registry.deubert.it:5000/db-databuilder/db-preloaded-01
    build: ./etc
    environment:
      BASE_IMAGE: ${BASE_IMAGE}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${DATABASE_NAME}
      #MYSQL_USER: ${DATABASE_USER}
      #MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
    - ./wait-for-it.sh:/tmp/wait-for-it.sh