version: '3'

services:
  db-preloaded:
    image: ${TARGET_IMAGE}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${DATABASE_NAME}
      #MYSQL_USER: ${DATABASE_USER}
      #MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./wait-for-it.sh:/tmp/wait-for-it.sh
      - ./show-dbinfo.sh:/tmp/show-dbinfo.sh
