version: '3'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${DATABASE_NAME}
      #MYSQL_USER: ${DATABASE_USER}
      #MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    user: jenkins
    volumes:
    - ./examples/01-simple:/docker-entrypoint-initdb.d/
    - ./data:/var/lib/mysql
    - ./wait-for-it.sh:/tmp/wait-for-it.sh